name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=mon-repo
            -Dsonar.sources=.
            -Dsonar.host.url=http://136.114.55.43:9000
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

